import json

class Devices():
    nivel_tanque = '{"STATUS_IP":"NÃO INICIADO","STATUS_VALVULA_SOLENOIDE":"NÃO CONECTADO","STATUS_NIVEL":"NÃO CONECTADO","STATUS_NIVEL_SIFAO": "","DESLIGA_ENCHE_TANQUE":"DESLIGA_ENCHE_TANQUE","ENCHE_TANQUE":"ENCHE_TANQUE"}'
    arduino = '{"STATUS FREQUENCIA":0, "STATUS PRESSAO":0, "STATUS_INVERSOR":"NÃO CONECTADO", "STATUS H2S":"", "STATUS RESET INV":"", "STATUS RESET 12V": "", "STATUS BOMBA":"", "STATUS ANALOG VALUE":0, "ENVIAR SERIAL":"", "STOP TROCA":"", "STOP TESTE":""}'
    bomba = '{"ZERA_OPERACOES": "", "STATUS_TEMP": "", "BOMBA": "", "STATUS_REGRESSIVA": "","STATUS_REGRESSIVA": "", "STATUS_HORA_OPERACAO": "", "NOME": ""}'
    acesso_eten = '{"STATUS_PORTA": "NÃO CONECTADO","STATUS_PWM": "NÃO CONECTADO","STATUS_TAG": "NÃO CONECTADO","STATUS_IP": "NÃO CONECTADO","STATUS_MAC": "","TESTE": "TESTE","STATUS_TEMPO_OPERACAO": "","GRAVA_TAG,66 27 73 C9": "GRAVA_TAG,66 27 73 C9","LISTA_TAGS": "LISTA_TAGS","ABRE": "FECHA","FECHA": "FECHA","PARA": "PARA"}'
    valvula_simples = '{"STATUS_SINAL_WIFI":"", "STATUS_TEMPO_OPERACAO":0,"STATUS_MAC":"", "STATUS_VALVULA":"", "STATUS_IP":"", "STATUS_CONTA_MOV":"", "OPERACOES":"OPERACOES", "LOOP":"", "ZERA_OPERACOES":"ZERA_OPERACOES", "STATUS_TEMPO_OPERACAO":0, "STATUS_VALVULA":"NÃO CONECTADO", "STATUS_IP":"NÃO CONECTADO", "NOME":"", "ABRE":"ABRE", "FECHA":"FECHA", "RESET":"RESET"}'
    valvula_cabine = '{"STATUS_FLUXO_DE_AR":0, "STATUS_SINAL_WIFI":"", "STATUS_TEMPO_OPERACAO":0, "STATUS_VALVULA":"NÃO CONECTADO", "STATUS_IP":"NÃO CONECTADO", "STATUS_CONTA_MOV":"", "OPERACOES":"OPERACOES", "LOOP":"", "ZERA_OPERACOES":"ZERA_OPERACOES", "STATUS_TEMPO_OPERACAO":"NÃO INICIADO", "STATUS_VALVULA":"NÃO CONECTADO", "STATUS_IP":"NÃO CONECTADO", "NOME":"", "ABRE":"ABRE", "FECHA":"FECHA", "RESET":"RESET", "CALIB_MAF":"CALIB_MAF", "ZERA_M3":"ZERA_M3", "DEBUG":"DEBUG", "CALIB_MAF":"CALIB_MAF", "HAB_BOT":"HAB_BOT"}'
    evaporadora = '{"LOOP": "", "S_IP": "", "S_D_RES": "", "S_RES": "", "S_TEMP": "", "S_COL": "", "S_EVAP": "", "S_WIFI": "", "S_MAC": "", "S_FEED": false, "S_C_MOV": "", "S_T_OP": "NAO INICIADO", "S_VAL": "NÃO CONECTADO", "ABRE": "ABRE", "ZERA_OPERACOES": "", "FECHA": "FECHA", "RESET": "", "LIGA_RESISTENCIA": "", "DESLIGA_RESISTENCIA": "", "NOME": ""}'
    evaporadora_sem_valvula = '{"STATUS_NIVEL_EVAPORADOR":"NÃO CONECTADO","STATUS_RESISTENCIA":"DESLIGADO","STATUS_DURACAO_RESISTENCIA": "0","STATUS_VALVULA": "0","STATUS_IP": "0","LIGA_RESISTENCIA":"LIGA_RESISTENCIA","ABRE_VALVULA":"ABRE_VALVULA","FECHA_VALVULA":"FECHA_VALVULA","DESLIGA_RESISTENCIA":"DESLIGA_RESISTENCIA"}'
    coletora = '{"STATUS_NIVEL":"NÃO CONECTADO","STATUS_BOMBA":"DESLIGADO","STATUS_DURACAO_BOMBA": "0","STATUS_CORRENTE_BOMBA": "0","STATUS_IP":"NÃO CONECTADO","LIGA_BOMBA":"LIGA_BOMBA","DESLIGA_BOMBA":"DESLIGA_BOMBA"}'
    CONTROLADORES = {
"ARDUINO":json.loads(arduino),
"EVAPORADOR_CABINE_2":{"STATUS_NIVEL_TANQUE":"NÃO CONECTADO","STATUS_NIVEL_EVAPORADOR":"NÃO CONECTADO","STATUS_RESISTENCIA":"DESLIGADO","STATUS_DURACAO_RESISTENCIA": 0,"STATUS_IP":"NÃO CONECTADO","LIGA_RESISTENCIA":"LIGA_RESISTENCIA","DESLIGA_RESISTENCIA":"DESLIGA_RESISTENCIA"},
                                                 
"BOMBA":{"ZERA_OPERACOES":"", "STATUS_TEMP":"", "BOMBA":"","STATUS_REGRESSIVA":"", "STATUS_REGRESSIVA":"", "STATUS_HORA_OPERACAO":"", "NOME":""},  

"VALVULA_CABINE_1":json.loads(valvula_cabine),
"ACESSO_ETEN":{
                "STATUS_PORTA":"NÃO CONECTADO",
                "STATUS_PWM":"NÃO CONECTADO",
                "STATUS_TAG":"NÃO CONECTADO",
                "STATUS_IP":"NÃO CONECTADO",
                "STATUS_MAC":"",
                "TESTE":"TESTE",
                "STATUS_TEMPO_OPERACAO":"",
                "ABRE":"FECHA",
                "PWM:400":"PWM:400",
                "FECHA":"FECHA",
                "PARA":"PARA"},
                


"679EE0_BOMBA":{"BOMBA":"","STATUS_REGRESSIVA":"", "STATUS_REGRESSIVA":"", "STATUS_HORA_OPERACAO":"", "NOME":""},
#~ "COMANDOS":{"ABRE TODAS":"", "FECHA TODAS":"", "ABRE_AMARELA":"", "FECHA AMARELA":"", "ABRE AZUL":"", "FECHA AZUL":"" , "ABRE CABINE":"", "FECHA CABINE":"", "STATUS":""} ,
"VALVULA_AM_ESQ":{**json.loads(valvula_simples), **{"COD_BLOCO":"BL_001", "COD_SUB_BLOCO":"SUB_001"}},
"VALVULA_AM_DIR":{**json.loads(valvula_simples), **{"COD_BLOCO":"BL_001", "COD_SUB_BLOCO":"SUB_001"}},
"VALVULA_AZ_DIR":{**json.loads(valvula_simples), **{"COD_BLOCO":"BL_001", "COD_SUB_BLOCO":"SUB_001"}},
"VALVULA_AZ_ESQ":{**json.loads(valvula_simples), **{"COD_BLOCO":"BL_001", "COD_SUB_BLOCO":"SUB_001"}},
"VALVULA_AZ_2":{**json.loads(valvula_simples), **{"COD_BLOCO":"BL_001", "COD_SUB_BLOCO":"SUB_001"}},
}

